320-manager
swclabs/swipe pull request #556
Opened 2024-09-30 07:02 UTC by anthony2704

In this repository, I will implement UI/ UX for inventory in manager, which link to API via Axios.

2024-09-30 08:01 UTC, kyeranyo requested changes
Some checks didn't pass

2024-09-30 10:15 UTC, anthony2704 commented
I have checked delete function, its all good now. I pushed test which returns ID of inventory when deleting, it returned the correct ID of inventory we choose to delete.
Anyway, we have some check failed here, I see it comes from products and dashboard

2024-10-01 08:28 UTC, kyeranyo commented
@anthony2704 Please reading build log !!

2024-10-04 05:25 UTC, kyeranyo approved these changes

2024-10-04 05:26 UTC, merged